### ISSUE TITLE
PWA not installable

### ISSUE THREAD

**Issue by wise-introvert** [samrith-s/vaccine-notifier#1]
Not sure if this an issue on my end but the application doesn't seem to be triggering the "Add to home screen" (Called the "Installable" property in a PWA) option on any of my devices. 

Screenshot of the address bar, where the install icon is supposed to appear:
Brave Browser:
![Brave](https://user-images.githubusercontent.com/66718300/116999518-58b6a400-acfd-11eb-86ae-4d188f9e7104.png)
Chrome:
![Chrome](https://user-images.githubusercontent.com/66718300/117000605-f2cb1c00-acfe-11eb-8b0d-02edf1383c6f.png)

BTW: An awesome idea, perfectly executed! Kudos to you :)

**Comment by samrith-s** [comment]
@wise-introvert Thank you for the report. I am trying to actually make this a bit better currently. Though on Android, I can add it to the home screen. I'll check why that's not happening on Chrome!

**Comment by wise-introvert** [comment]
Thanks! Weird enough: I'm not able to install it on my android device... Anyways, great job so far, looking forward to the next version 😄
